# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 600)
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainwindow = QtWidgets.QFrame(self.centralwidget)
        self.mainwindow.setStyleSheet("#mainwindow\n"
"{\n"
"  background-color: rgba(255, 0, 0, 0)\n"
"}")
        self.mainwindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainwindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainwindow.setObjectName("mainwindow")
        self.pnlLogin = QtWidgets.QFrame(self.mainwindow)
        self.pnlLogin.setGeometry(QtCore.QRect(139, 19, 491, 521))
        self.pnlLogin.setStyleSheet("#pnlLogin\n"
"{\n"
"   background: yellow;\n"
"   border-width:10px;\n"
"   border-color: rgb(1,0,0);\n"
"   border-radius:15px;\n"
"}")
        self.pnlLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pnlLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlLogin.setObjectName("pnlLogin")
        self.verticalLayout.addWidget(self.mainwindow)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
